apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: fire-support-apis
    - op: replace
      path: /metadata/labels/app
      value: fire-support-apis
    - op: replace
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: fire-support
  target:
    name: apis
- patch: |-
    - op: replace
      path: /metadata/name
      value: fire-support-ui
    - op: replace
      path: /metadata/labels/app
      value: fire-support-ui
    - op: replace
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: fire-support
  target:
    name: ui
- patch: |-
    - op: replace
      path: /spec/to/name
      value: fire-support-ui
  target:
    kind: Route
    name: ui
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value 
      value: fire-support-apis
    - op: replace
      path: /spec/selector/matchLabels/app
      value: fire-support-ui
    - op: replace
      path: /spec/template/metadata/labels/app
      value: fire-support-ui
  target:
    kind: Deployment
    name: ui
- patch: |-
    - op: replace
      path: /spec/selector/matchLabels/app
      value: fire-support-apis
    - op: replace
      path: /spec/template/metadata/labels/app
      value: fire-support-apis            
  target:
    kind: Deployment
    name: apis
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: fire-support-apis
  target:
    kind: Service
    name: apis
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: fire-support-apis
  target:
    kind: Service
    name: apis-rhsi
- patch: |-
    - op: replace
      path: /metadata/name
      value: fire-support-apis-rhsi
    - op: replace
      path: /metadata/labels/app
      value: fire-support-apis
    - op: replace
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: fire-support
  target:
    name: apis-rhsi 
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: fire-support-ui
  target:
    kind: Service
    name: ui
configMafire-supportenerator:
- name: app-config
  behavior: merge
  literals:
  - system=Fire-Support
  - app_name=Fire-Support