# gitops filder

# create placement objects
oc create -f placements/apps-placement.yaml
oc create -f placements/location-placement.yaml

# deploy dashboard app
oc create -f dashboard-applicationset.yaml -n openshift-gitops

# create hub-apis sa and generate token with cluster-admin role
oc create sa hub-apis
oc create token hub-apis
# a secret will be created with the token that can be used fot he API calls (hub-apis-token-XXXXX)
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:hub-ns:hub-apis
# curl -k -H "Authorization: Bearer TOOKEN" "https://api.cluster-sql9s.sql9s.[Base DNS Domain]:6443/apis/policy.open-cluster-management.io/v1/namespaces/openshift-gitops/policies/hub-ns"


# create hub-apis-token secret
cat <<EOF | oc apply -f -
kind: Secret
apiVersion: v1
metadata:
  name: hub-apis-token
  namespace: hub-ns
data:
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrRlJOR2RYVFhkdVltaHhUa1EyVFZveU1IZ3pkRWRHVVRRMVgweFNlWEZoWlZKZmFqRjBjSG90V2swaWZRLmV5SmhkV1FpT2xzaWFIUjBjSE02THk5cmRXSmxjbTVsZEdWekxtUmxabUYxYkhRdWMzWmpJbDBzSW1WNGNDSTZNVGN5TmpFM01EUXpNeXdpYVdGMElqb3hOekkyTVRZMk9ETXpMQ0pwYzNNaU9pSm9kSFJ3Y3pvdkwydDFZbVZ5Ym1WMFpYTXVaR1ZtWVhWc2RDNXpkbU1pTENKcmRXSmxjbTVsZEdWekxtbHZJanA3SW01aGJXVnpjR0ZqWlNJNkltaDFZaTF1Y3lJc0luTmxjblpwWTJWaFkyTnZkVzUwSWpwN0ltNWhiV1VpT2lKb2RXSXRZWEJwY3lJc0luVnBaQ0k2SWpJek1qUTJOemsxTFRZMU9UZ3RORFprWVMxaFlqUmxMVGd4WW1JeE9UQm1aakZpTVNKOWZTd2libUptSWpveE56STJNVFkyT0RNekxDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZhSFZpTFc1ek9taDFZaTFoY0dsekluMC5uYlVTUFpjZHFXMmQ1NU80ZmVpQmpqNXphS184UmF2SjRGaGNUMm80QnVnNXUtY1hzT01Fa3JmenVzTlFUZHlLYXdVY0c0WnFlTWd0cEFFZ3VZNGdjNjUxalJGWVcyanJ1dDRyQXJ2NFBrMHk2V004UEppQXJ4N2pRUXZXTU9OckdPZkVVcE5uMHF2dUFUaC1QdXlROUs1a0NSckRxWVBuWTh2T3IwUXRuYXZXR2JoYm5pdDB1WWxLM0N3SC1uaGlxQ3Y3MTBGdFNkTEM3dURfY09ielRQWHpSTEJhVldnZWVKOVgtcFBlSTF2RklhR2hkeDY2VmxEU0JoMTR2TU1hSGZqTnVoT1B0XzMyaHpZUjAzN2t2SzBXTjkxVjJ6THpYdGFpYjhTemp0QkhuS29OVWFJOFdwc3hQQkNLZGdxTmNKVVQ5cTllWkZxVHVxSXpsLU1QZHdIVDZMdXpYSWFRazBLZEtLV3YwYWdGVmIySGVWSl8tVVVCeGd1RTlZc0U2dkZ4M2xUNTd6NWdUZ2hxVWU0cjhZNWZ2NkNVb05UTVcxUk9LZ1B0dW5nMzlkRXJtY2FjN1huWUVpemhnNDNqeEdqVTcyQlRhUGpKbkVGa3ltdUd2NkJTRmFIcXN1WlR4LVktSHVTRHlMZ0hFbHU4UWJNcWphYWVOUFRiY3o1aE5kSEdLWExTd2JRRWdqT1JIeGhVM0lDQ210R0pCRXZRM3VOMnRSZ2FtZlBoVW9sTFVxbE1XQXdJWmdjUUZmenpLZWtxeHZrNHAtNExnYk1MMlg2RG01Y1pTa1FyRUdPT2JaeGF3M1NoMzg2aGgwdmV5bDRzem9CQWNULWtpT2dYOFpmVkJoSm1IbHNGcGdhRVo5dDRJRXY1ejlOUmtyRXhsUXlCNTVLRWE3aw==
type: Opaque
EOF


# delete 
#oc delete  -f dashboard-applicationset.yaml -n openshift-gitops
